create table "public"."parcels_monitoring" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "tracking_id" character varying,
    "carrier_id" bigint,
    "user_id" uuid
);


alter table "public"."parcels_monitoring" enable row level security;

CREATE UNIQUE INDEX parcels_monitoring_pkey ON public.parcels_monitoring USING btree (id);

alter table "public"."parcels_monitoring" add constraint "parcels_monitoring_pkey" PRIMARY KEY using index "parcels_monitoring_pkey";

alter table "public"."parcels_monitoring" add constraint "parcels_monitoring_carrier_id_fkey" FOREIGN KEY (carrier_id) REFERENCES carriers(id) not valid;

alter table "public"."parcels_monitoring" validate constraint "parcels_monitoring_carrier_id_fkey";

alter table "public"."parcels_monitoring" add constraint "parcels_monitoring_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."parcels_monitoring" validate constraint "parcels_monitoring_user_id_fkey";


